import type { Branch, Customer, Vehicle, Technician, Part, Supplier, Job } from './types';

// ── Branches ──────────────────────────────────────────────────────────────────

export const branches: Branch[] = [
  { id: 'br-00', name: 'Vereeniging' },
  { id: 'br-01', name: 'East Rand' },
  { id: 'br-02', name: 'Northgate' },
  { id: 'br-03', name: 'South Rand' },
];

// ── Customers ─────────────────────────────────────────────────────────────────

export const customers: Customer[] = [
  {
    id: 'cust-01',
    name: 'Pieter van der Merwe',
    phone: '+27 82 341 9072',
    email: 'pieter.vdm@gmail.com',
    address: '14 Ou Wapad Str, Brakpan, 1541',
    notes: 'Fleet owner — three Amaroks on the road. Prefers morning drop-offs.',
  },
  {
    id: 'cust-02',
    name: 'Nomsa Dlamini',
    phone: '+27 71 508 6341',
    email: 'nomsa.dlamini@webmail.co.za',
    address: '82 Protea Ave, Soweto, 1804',
    notes: 'Referred by Pieter. Very punctual, always pays cash.',
  },
  {
    id: 'cust-03',
    name: 'Riaan Botha',
    phone: '+27 83 762 1450',
    email: 'riaanb@constructsa.co.za',
    address: '7 Steel Road, Alberton North, 1449',
    notes: 'Construction company account. Invoice to Construct SA (Pty) Ltd.',
  },
  {
    id: 'cust-04',
    name: 'Fatima Moosa',
    phone: '+27 73 204 8819',
    email: 'fatima@moosatransport.co.za',
    address: '33 Lenasia Drive, Lenasia, 1827',
    notes: 'Transport business. Needs vehicles back same-day where possible.',
  },
  {
    id: 'cust-05',
    name: 'Andile Khumalo',
    phone: '+27 84 903 5627',
    email: 'andile.khumalo@outlook.com',
    address: '5 Jacaranda Close, Edenvale, 1609',
    notes: 'Personal vehicle only. Prefers WhatsApp updates over calls.',
  },
  {
    id: 'cust-06',
    name: 'Christa Pretorius',
    phone: '+27 82 617 4403',
    email: 'c.pretorius@farmersco.co.za',
    address: 'Plot 44, Bronkhorstspruit Rd, Rayton, 1001',
    notes: 'Farm vehicle — high mileage and heavy mud use. Seasonal visits.',
  },
  {
    id: 'cust-07',
    name: 'Desmond Nkosi',
    phone: '+27 76 388 2741',
    email: 'desnkosi@gmail.com',
    address: '19 Thaba Nchu Str, Vosloorus, 1475',
    notes: 'Claims specialist. Has extended warranty — verify on every job.',
  },
  {
    id: 'cust-08',
    name: 'Liezel Swanepoel',
    phone: '+27 83 491 6058',
    email: 'liezel.s@garagemotors.co.za',
    address: '2 Trade Park Blvd, Boksburg, 1459',
    notes: 'Trade account — Garage Motors. Discount tier B applies.',
  },
];

// ── Vehicles ──────────────────────────────────────────────────────────────────

export const vehicles: Vehicle[] = [
  {
    id: 'veh-01',
    customerId: 'cust-01',
    make: 'Volkswagen',
    model: 'Amarok 3.0 TDI V6 Highline 4Motion',
    year: 2021,
    vin: 'WV1ZZZ2HZMX041887',
    registration: 'GP 48 JK LM',
    mileage: 112450,
    color: 'Deep Black Pearl',
    notes: 'Bull bar fitted. ARB roof rack. Previous oil leak at rocker cover — monitor.',
  },
  {
    id: 'veh-02',
    customerId: 'cust-01',
    make: 'Volkswagen',
    model: 'Amarok 2.0 BiTDI Comfortline 4Motion',
    year: 2019,
    vin: 'WV1ZZZ2HZKX018294',
    registration: 'GP 17 RW PQ',
    mileage: 187300,
    color: 'Reflex Silver',
    notes: 'Fleet unit #2. DSG recently replaced at 180k.',
  },
  {
    id: 'veh-03',
    customerId: 'cust-01',
    make: 'Volkswagen',
    model: 'Amarok 2.0 TDI Trendline 4x2',
    year: 2018,
    vin: 'WV1ZZZ2HZJX004412',
    registration: 'GP 33 KT MN',
    mileage: 224100,
    color: 'Candy White',
    notes: 'Fleet unit #3. High-mileage — timing chain due.',
  },
  {
    id: 'veh-04',
    customerId: 'cust-02',
    make: 'Volkswagen',
    model: 'Amarok 3.0 TDI V6 Aventura 4Motion',
    year: 2022,
    vin: 'WV1ZZZ2HZNX072153',
    registration: 'GP 91 BZ XQ',
    mileage: 54870,
    color: 'Oryx White Pearl',
    notes: 'Leather interior, panoramic sunroof. Keep clean on entry.',
  },
  {
    id: 'veh-05',
    customerId: 'cust-03',
    make: 'Volkswagen',
    model: 'Amarok 2.0 BiTDI Highline 4Motion',
    year: 2020,
    vin: 'WV1ZZZ2HZLX029371',
    registration: 'GP 55 CF DE',
    mileage: 143600,
    color: 'Tungsten Silver',
    notes: 'Construction site use. Cab Guard fitted. Frequent diff and brake checks.',
  },
  {
    id: 'veh-06',
    customerId: 'cust-04',
    make: 'Volkswagen',
    model: 'Transporter T6.1 2.0 TDI 110kW',
    year: 2021,
    vin: 'WV2ZZZ7HZMH203841',
    registration: 'GP 22 DT RS',
    mileage: 98750,
    color: 'Acapulco Blue',
    notes: 'Panel van configuration. Roof vent fitted by third party.',
  },
  {
    id: 'veh-07',
    customerId: 'cust-05',
    make: 'Volkswagen',
    model: 'Amarok 2.0 TDI Highline 4x2',
    year: 2023,
    vin: 'WV1ZZZ2HZPX091042',
    registration: 'GP 06 WM ST',
    mileage: 31200,
    color: 'Atacama Brown',
    notes: 'Under VW new vehicle warranty until 2026-06. Log all repairs.',
  },
  {
    id: 'veh-08',
    customerId: 'cust-06',
    make: 'Volkswagen',
    model: 'Amarok 2.0 BiTDI Comfortline 4Motion',
    year: 2017,
    vin: 'WV1ZZZ2HZHX002194',
    registration: 'GP 74 PR EF',
    mileage: 289500,
    color: 'Starlight Blue',
    notes: 'Farm vehicle. Expect mud contamination in brake and diff components.',
  },
  {
    id: 'veh-09',
    customerId: 'cust-07',
    make: 'Volkswagen',
    model: 'Amarok 3.0 TDI V6 Comfortline 4Motion',
    year: 2022,
    vin: 'WV1ZZZ2HZNX068407',
    registration: 'GP 14 QS UV',
    mileage: 67340,
    color: 'Limestone Grey',
    notes: 'Extended warranty active. Document all faults and parts numbers carefully.',
  },
  {
    id: 'veh-10',
    customerId: 'cust-08',
    make: 'Volkswagen',
    model: 'Polo 1.0 TSI Comfortline',
    year: 2020,
    vin: 'WVWZZZ6RZLY041938',
    registration: 'GP 81 GT OP',
    mileage: 78900,
    color: 'Flash Red',
    notes: 'Trade-in vehicle being prepped for resale. Full service required.',
  },
];

// ── Technicians ───────────────────────────────────────────────────────────────

export const technicians: Technician[] = [
  {
    id: 'tech-01',
    name: 'Kobus Engelbrecht',
    role: 'Master Technician',
    phone: '+27 82 514 3309',
    email: 'kobus.e@ammaspares.co.za',
    skills: ['VW DSG Transmission', 'V6 TDI Engine', 'Electrical Diagnostics', 'VCDS Coding'],
    isActive: true,
  },
  {
    id: 'tech-02',
    name: 'Sipho Mthembu',
    role: 'Senior Technician',
    phone: '+27 73 881 4127',
    email: 'sipho.m@ammaspares.co.za',
    skills: ['Timing Chain & Belt', 'Engine Overhaul', 'Cooling Systems', 'Suspension'],
    isActive: true,
  },
  {
    id: 'tech-03',
    name: 'Jacques Fourie',
    role: 'Technician',
    phone: '+27 84 722 6550',
    email: 'jacques.f@ammaspares.co.za',
    skills: ['Brakes', 'Clutch & Flywheel', 'Exhaust Systems', 'Diff & Transfer Case'],
    isActive: true,
  },
  {
    id: 'tech-04',
    name: 'Thabiso Molefe',
    role: 'Apprentice Technician',
    phone: '+27 76 304 9812',
    email: 'thabiso.m@ammaspares.co.za',
    skills: ['Oil Services', 'Tyre Fitting', 'Wheel Alignment', 'Air Filter Replacement'],
    isActive: true,
  },
  {
    id: 'tech-05',
    name: 'Werner Kriel',
    role: 'Diagnostic Specialist',
    phone: '+27 83 668 0374',
    email: 'werner.k@ammaspares.co.za',
    skills: ['VCDS Advanced Diagnostics', 'ECU Remapping Prep', 'Electrical Fault Finding', 'AdBlue Systems'],
    isActive: false,
  },
];

// ── Suppliers ─────────────────────────────────────────────────────────────────

export const suppliers: Supplier[] = [
  {
    id: 'sup-01',
    name: 'VW Genuine Parts SA',
    contactName: 'Marinda Nel',
    phone: '+27 11 672 4400',
    email: 'parts@vwsa.co.za',
    address: '1 Auto Mall Drive, Isando, 1600',
    notes: 'OEM parts only. 3–5 business day lead time. Account #VW-AMMA-0041.',
  },
  {
    id: 'sup-02',
    name: 'AutoZone Trade',
    contactName: 'Bongani Sithole',
    phone: '+27 11 896 1100',
    email: 'trade@autozone.co.za',
    address: 'Unit 4, Trade Park, Boksburg, 1459',
    notes: 'Aftermarket and economy parts. Next-day delivery available. Net 30 terms.',
  },
  {
    id: 'sup-03',
    name: 'Rowe Lubricants SA',
    contactName: 'Anke Venter',
    phone: '+27 21 552 8800',
    email: 'orders@rowelubricants.co.za',
    address: '17 Paarden Eiland Rd, Cape Town, 7405',
    notes: 'Preferred oil supplier. Bulk 20L drums. Amarok-spec 5W-30 in stock.',
  },
];

// ── Parts ─────────────────────────────────────────────────────────────────────

export const parts: Part[] = [
  {
    id: 'part-01',
    name: 'Timing Chain Kit — 2.0 TDI (CDCA/CSHA)',
    partNumber: '03L-109-229-B',
    category: 'Engine',
    type: 'Genuine',
    stock: 4,
    costPrice: 4200,
    sellingPrice: 6800,
    supplier: 'sup-01',
    notes: 'Includes chain, tensioner, and guide rails. Replace every 120k km.',
    reorderLevel: 2,
  },
  {
    id: 'part-02',
    name: 'Timing Chain Kit — 3.0 TDI V6',
    partNumber: '059-109-229-AK',
    category: 'Engine',
    type: 'Genuine',
    stock: 2,
    costPrice: 8900,
    sellingPrice: 13500,
    supplier: 'sup-01',
    notes: 'V6 fitment only. Dual chain system. Labour-intensive — allow 8 hours.',
    reorderLevel: 1,
  },
  {
    id: 'part-03',
    name: 'Front Brake Pad Set — Amarok',
    partNumber: '2H0-698-151-A',
    category: 'Brakes',
    type: 'Genuine',
    stock: 12,
    costPrice: 780,
    sellingPrice: 1250,
    supplier: 'sup-01',
    notes: 'OEM compound. Suits all Amarok variants with 330mm disc.',
    reorderLevel: 4,
  },
  {
    id: 'part-04',
    name: 'Front Brake Pad Set — Economy',
    partNumber: 'AZ-BP-VW-AMR-F',
    category: 'Brakes',
    type: 'Economy',
    stock: 18,
    costPrice: 390,
    sellingPrice: 680,
    supplier: 'sup-02',
    notes: 'Bremtec compound. Suitable for standard road use.',
    reorderLevel: 6,
  },
  {
    id: 'part-05',
    name: 'Rear Brake Disc Pair — Amarok',
    partNumber: '2H0-615-601-C',
    category: 'Brakes',
    type: 'Genuine',
    stock: 6,
    costPrice: 1650,
    sellingPrice: 2600,
    supplier: 'sup-01',
    notes: 'Vented rear disc. Min thickness 18mm. Replace as a pair.',
    reorderLevel: 2,
  },
  {
    id: 'part-06',
    name: 'DSG Gearbox Oil — 6L Kit (DQ250)',
    partNumber: 'G-052-182-A2',
    category: 'Transmission',
    type: 'Genuine',
    stock: 10,
    costPrice: 1100,
    sellingPrice: 1800,
    supplier: 'sup-01',
    notes: 'VW G052182 spec. 6-litre kit sufficient for full DQ250 DSG service.',
    reorderLevel: 3,
  },
  {
    id: 'part-07',
    name: 'Rear Differential Oil — Haldex 4th Gen',
    partNumber: 'G-052-175-A2',
    category: 'Drivetrain',
    type: 'Genuine',
    stock: 8,
    costPrice: 520,
    sellingPrice: 890,
    supplier: 'sup-01',
    notes: 'Required for Haldex rear diff service. 1L bottle, full fill ~0.85L.',
    reorderLevel: 3,
  },
  {
    id: 'part-08',
    name: 'Engine Oil — Rowe 5W-30 (5L)',
    partNumber: 'RW-5W30-VW504-5L',
    category: 'Lubricants',
    type: 'New',
    stock: 35,
    costPrice: 320,
    sellingPrice: 550,
    supplier: 'sup-03',
    notes: 'VW 504.00/507.00 spec. Suits all Amarok 2.0 and 3.0 TDI engines.',
    reorderLevel: 10,
  },
  {
    id: 'part-09',
    name: 'Oil Filter — 2.0 TDI',
    partNumber: '03L-115-562',
    category: 'Engine',
    type: 'Genuine',
    stock: 20,
    costPrice: 145,
    sellingPrice: 260,
    supplier: 'sup-01',
    notes: 'Cartridge-style filter. Always replace with oil service.',
    reorderLevel: 8,
  },
  {
    id: 'part-10',
    name: 'Air Filter — Amarok 2.0 TDI',
    partNumber: '2H0-129-620-A',
    category: 'Engine',
    type: 'Genuine',
    stock: 14,
    costPrice: 310,
    sellingPrice: 520,
    supplier: 'sup-01',
    notes: 'Panel-style airbox filter. Replace every 30k km or sooner in dusty conditions.',
    reorderLevel: 5,
  },
  {
    id: 'part-11',
    name: 'Front CV Axle Shaft — Left (4Motion)',
    partNumber: '2H0-407-271-C',
    category: 'Drivetrain',
    type: 'Used',
    stock: 3,
    costPrice: 1900,
    sellingPrice: 3200,
    supplier: 'sup-02',
    notes: 'Quality-checked used unit from stripped Amarok. 12-month warranty.',
    reorderLevel: 1,
  },
  {
    id: 'part-12',
    name: 'Intercooler — 2.0 BiTDI',
    partNumber: '2H0-145-805-C',
    category: 'Engine',
    type: 'Used',
    stock: 2,
    costPrice: 2800,
    sellingPrice: 4500,
    supplier: 'sup-02',
    notes: 'Pressure-tested used unit. Suits BiTDI 132kW and 120kW variants.',
    reorderLevel: 1,
  },
];

// ── Jobs ──────────────────────────────────────────────────────────────────────

export const jobs: Job[] = [
  {
    id: 'job-001',
    customerId: 'cust-03',
    vehicleId: 'veh-05',
    title: 'DSG 7-Speed Service + Haldex Rear Diff',
    description: 'Customer reports jerky low-speed shifting and slight shudder under load. Full DQ500 service including mechatronic flush. Haldex diff oil also due.',
    status: 'in-progress',
    priority: 'high',
    assignedTechnicianIds: ['tech-01'],
    estimatedCost: 8500,
    finalCost: null,
    startDate: '2026-04-21',
    dueDate: '2026-04-23',
    completedAt: null,
    parts: [
      { partId: 'part-06', partName: 'DSG Gearbox Oil — 6L Kit (DQ250)', quantity: 1, unitPrice: 1800 },
      { partId: 'part-07', partName: 'Rear Differential Oil — Haldex 4th Gen', quantity: 1, unitPrice: 890 },
    ],
    notes: 'Pre-authorised up to R9,000. Call Riaan before exceeding.',
  },
  {
    id: 'job-002',
    customerId: 'cust-01',
    vehicleId: 'veh-03',
    title: 'Timing Chain Replacement — 2.0 TDI High Mileage',
    description: 'Vehicle at 224k km. Rattling on cold start confirmed — timing chain stretch. Full kit replacement including tensioner and guides. Customer also requesting oil service.',
    status: 'in-progress',
    priority: 'high',
    assignedTechnicianIds: ['tech-02', 'tech-04'],
    estimatedCost: 18500,
    finalCost: null,
    startDate: '2026-04-20',
    dueDate: '2026-04-24',
    completedAt: null,
    parts: [
      { partId: 'part-01', partName: 'Timing Chain Kit — 2.0 TDI (CDCA/CSHA)', quantity: 1, unitPrice: 6800 },
      { partId: 'part-08', partName: 'Engine Oil — Rowe 5W-30 (5L)', quantity: 2, unitPrice: 550 },
      { partId: 'part-09', partName: 'Oil Filter — 2.0 TDI', quantity: 1, unitPrice: 260 },
    ],
    notes: 'Pieter approved via WhatsApp. Fleet priority — needs back ASAP.',
  },
  {
    id: 'job-003',
    customerId: 'cust-02',
    vehicleId: 'veh-04',
    title: 'Full Service — 60 000 km Interval',
    description: 'V6 Aventura 60k service. Engine oil and filter, air filter, pollen filter, brake fluid, and visual inspection.',
    status: 'completed',
    priority: 'medium',
    assignedTechnicianIds: ['tech-04'],
    estimatedCost: 3800,
    finalCost: 3650,
    startDate: '2026-04-14',
    dueDate: '2026-04-14',
    completedAt: '2026-04-14',
    parts: [
      { partId: 'part-08', partName: 'Engine Oil — Rowe 5W-30 (5L)', quantity: 2, unitPrice: 550 },
      { partId: 'part-09', partName: 'Oil Filter — 2.0 TDI', quantity: 1, unitPrice: 260 },
      { partId: 'part-10', partName: 'Air Filter — Amarok 2.0 TDI', quantity: 1, unitPrice: 520 },
    ],
    notes: 'Completed on time. No faults found. Next service due 2026-10.',
  },
  {
    id: 'job-004',
    customerId: 'cust-04',
    vehicleId: 'veh-06',
    title: 'Intercooler Pipe Leak Diagnosis & Repair',
    description: 'Customer reports power loss and black smoke under load. Suspected intercooler pipe split or loose coupling. Full boost system inspection.',
    status: 'waiting-parts',
    priority: 'high',
    assignedTechnicianIds: ['tech-02'],
    estimatedCost: 6200,
    finalCost: null,
    startDate: '2026-04-19',
    dueDate: '2026-04-22',
    completedAt: null,
    parts: [
      { partId: 'part-12', partName: 'Intercooler — 2.0 BiTDI', quantity: 1, unitPrice: 4500 },
    ],
    notes: 'Waiting on intercooler from AutoZone. ETA 2026-04-23. Notify Fatima.',
  },
  {
    id: 'job-005',
    customerId: 'cust-05',
    vehicleId: 'veh-07',
    title: 'Brake Pads & Disc Inspection — 30k Check',
    description: 'Warranty inspection at 30,000 km. Customer reports mild brake squeal after standing overnight. Inspect pads, discs, and calipers. No replacement likely needed.',
    status: 'pending',
    priority: 'low',
    assignedTechnicianIds: ['tech-03'],
    estimatedCost: 1500,
    finalCost: null,
    startDate: '2026-04-23',
    dueDate: '2026-04-24',
    completedAt: null,
    parts: [],
    notes: 'Under new vehicle warranty. If pads are defective, claim via VW SA warranty portal.',
  },
  {
    id: 'job-006',
    customerId: 'cust-06',
    vehicleId: 'veh-08',
    title: 'Rear Brake Overhaul — Farm Vehicle',
    description: 'High-mileage farm Amarok. Rear discs corroded and pads worn to metal. Full rear brake kit replacement. Clean and lube sliding pins. Check hand brake cable.',
    status: 'completed',
    priority: 'high',
    assignedTechnicianIds: ['tech-03', 'tech-04'],
    estimatedCost: 7200,
    finalCost: 7450,
    startDate: '2026-04-08',
    dueDate: '2026-04-09',
    completedAt: '2026-04-09',
    parts: [
      { partId: 'part-04', partName: 'Front Brake Pad Set — Economy', quantity: 2, unitPrice: 680 },
      { partId: 'part-05', partName: 'Rear Brake Disc Pair — Amarok', quantity: 1, unitPrice: 2600 },
    ],
    notes: 'Corroded bleed nipple on RR caliper — replaced nipple at no charge. Good customer.',
  },
  {
    id: 'job-007',
    customerId: 'cust-07',
    vehicleId: 'veh-09',
    title: 'Extended Warranty Claim — Engine Oil Consumption',
    description: 'Customer reports excessive oil consumption (>0.5L per 1000 km). Under extended warranty. VCDS log, compression test, and leak-down test required for warranty submission.',
    status: 'pending',
    priority: 'medium',
    assignedTechnicianIds: ['tech-01', 'tech-05'],
    estimatedCost: 2200,
    finalCost: null,
    startDate: '2026-04-25',
    dueDate: '2026-04-28',
    completedAt: null,
    parts: [],
    notes: 'Warranty claim must be pre-authorised by VW SA. Werner to handle VCDS logging.',
  },
  {
    id: 'job-008',
    customerId: 'cust-08',
    vehicleId: 'veh-10',
    title: 'Pre-Sale Full Service — VW Polo',
    description: 'Trade-in Polo being prepared for resale. Full 90k service, cabin filter, brake fluid, tyre inspection, and VCDS fault clear.',
    status: 'in-progress',
    priority: 'medium',
    assignedTechnicianIds: ['tech-04'],
    estimatedCost: 4800,
    finalCost: null,
    startDate: '2026-04-22',
    dueDate: '2026-04-23',
    completedAt: null,
    parts: [
      { partId: 'part-08', partName: 'Engine Oil — Rowe 5W-30 (5L)', quantity: 1, unitPrice: 550 },
    ],
    notes: 'Garage Motors internal job. Bill to trade account — do not invoice customer directly.',
  },
  {
    id: 'job-009',
    customerId: 'cust-01',
    vehicleId: 'veh-01',
    title: 'V6 TDI Full Service + AdBlue Top-up',
    description: 'Annual 15k km service on the V6 Highline. Engine oil, filter, air filter, and AdBlue fill. Check diff oil levels and inspect undercarriage for mud build-up.',
    status: 'completed',
    priority: 'medium',
    assignedTechnicianIds: ['tech-01', 'tech-04'],
    estimatedCost: 5500,
    finalCost: 5320,
    startDate: '2026-04-01',
    dueDate: '2026-04-01',
    completedAt: '2026-04-01',
    parts: [
      { partId: 'part-08', partName: 'Engine Oil — Rowe 5W-30 (5L)', quantity: 3, unitPrice: 550 },
      { partId: 'part-09', partName: 'Oil Filter — 2.0 TDI', quantity: 1, unitPrice: 260 },
      { partId: 'part-10', partName: 'Air Filter — Amarok 2.0 TDI', quantity: 1, unitPrice: 520 },
    ],
    notes: 'AdBlue topped 18L. Next service in 15,000 km or October 2026.',
  },
  {
    id: 'job-010',
    customerId: 'cust-01',
    vehicleId: 'veh-02',
    title: '90k Service + DSG Filter Replace',
    description: 'Fleet Amarok #2. 90,000 km service interval. DSG external filter replacement (mechatronic not due). Oil, filters, and brake fluid change.',
    status: 'pending',
    priority: 'medium',
    assignedTechnicianIds: ['tech-01'],
    estimatedCost: 7200,
    finalCost: null,
    startDate: '2026-04-28',
    dueDate: '2026-04-29',
    completedAt: null,
    parts: [
      { partId: 'part-06', partName: 'DSG Gearbox Oil — 6L Kit (DQ250)', quantity: 1, unitPrice: 1800 },
      { partId: 'part-08', partName: 'Engine Oil — Rowe 5W-30 (5L)', quantity: 2, unitPrice: 550 },
      { partId: 'part-09', partName: 'Oil Filter — 2.0 TDI', quantity: 1, unitPrice: 260 },
    ],
    notes: 'Fleet vehicle #2. Pieter confirmed booking via WhatsApp 2026-04-20.',
  },
  {
    id: 'job-011',
    customerId: 'cust-04',
    vehicleId: 'veh-06',
    title: 'CV Boot Replacement — Left Front',
    description: 'Torn outer CV boot found during previous inspection. Grease thrown onto brake disc. Replace boot kit and repack with new grease. Check joint for wear.',
    status: 'completed',
    priority: 'medium',
    assignedTechnicianIds: ['tech-03'],
    estimatedCost: 3200,
    finalCost: 3100,
    startDate: '2026-03-28',
    dueDate: '2026-03-28',
    completedAt: '2026-03-28',
    parts: [
      { partId: 'part-11', partName: 'Front CV Axle Shaft — Left (4Motion)', quantity: 1, unitPrice: 3200 },
    ],
    notes: 'Joint itself still good — boot only needed. Quoted shaft as contingency.',
  },
  {
    id: 'job-012',
    customerId: 'cust-05',
    vehicleId: 'veh-07',
    title: 'VCDS Fault Code Scan & ECU Update',
    description: 'Dashboard warning light (engine management). Customer requests VCDS diagnostic scan and check for outstanding ECU software updates via ODIS.',
    status: 'completed',
    priority: 'low',
    assignedTechnicianIds: ['tech-05'],
    estimatedCost: 1800,
    finalCost: 1800,
    startDate: '2026-04-10',
    dueDate: '2026-04-10',
    completedAt: '2026-04-10',
    parts: [],
    notes: 'Fault: EGR valve soft code. Cleared — no recurrence in 1 week. ECU updated to latest.',
  },
  {
    id: 'job-013',
    customerId: 'cust-06',
    vehicleId: 'veh-08',
    title: 'Suspension Overhaul — Front End',
    description: 'Farm vehicle with severely worn front suspension. Replace both lower ball joints, front stabiliser drop links, and inspect shock absorbers. Wheel alignment required after.',
    status: 'waiting-parts',
    priority: 'high',
    assignedTechnicianIds: ['tech-02'],
    estimatedCost: 14500,
    finalCost: null,
    startDate: '2026-04-18',
    dueDate: '2026-04-26',
    completedAt: null,
    parts: [],
    notes: 'Ball joints ordered from AutoZone — ETA 2026-04-24. Shock absorbers in stock at sup-02.',
  },
  {
    id: 'job-014',
    customerId: 'cust-02',
    vehicleId: 'veh-04',
    title: 'Aircon Regas & Cabin Filter Replacement',
    description: 'Customer reports weak aircon output entering summer. Re-gas system (R1234yf refrigerant), check for leaks, replace cabin pollen filter.',
    status: 'pending',
    priority: 'low',
    assignedTechnicianIds: ['tech-04'],
    estimatedCost: 2400,
    finalCost: null,
    startDate: '2026-04-30',
    dueDate: '2026-05-02',
    completedAt: null,
    parts: [],
    notes: 'Refrigerant to be sourced on the day. Confirm R1234yf applicability for 2022 Aventura.',
  },
  {
    id: 'job-015',
    customerId: 'cust-03',
    vehicleId: 'veh-05',
    title: 'Front Brake Pad & Disc Replacement',
    description: 'Wear indicators triggered on front axle. Customer approved OEM pads. Measure and replace discs if below minimum thickness. Flush brake fluid.',
    status: 'cancelled',
    priority: 'medium',
    assignedTechnicianIds: ['tech-03'],
    estimatedCost: 6800,
    finalCost: null,
    startDate: '2026-04-16',
    dueDate: '2026-04-17',
    completedAt: null,
    parts: [
      { partId: 'part-03', partName: 'Front Brake Pad Set — Amarok', quantity: 1, unitPrice: 1250 },
      { partId: 'part-05', partName: 'Rear Brake Disc Pair — Amarok', quantity: 1, unitPrice: 2600 },
    ],
    notes: 'Cancelled — vehicle broke down at customer site and was towed elsewhere. Re-book pending.',
  },
];

// ── Helper Functions ───────────────────────────────────────────────────────────

export function getCustomerById(id: string) {
  return customers.find((c) => c.id === id) ?? null;
}

export function getVehicleById(id: string) {
  return vehicles.find((v) => v.id === id) ?? null;
}

export function getTechnicianById(id: string) {
  return technicians.find((t) => t.id === id) ?? null;
}

export function getPartById(id: string) {
  return parts.find((p) => p.id === id) ?? null;
}
